### ISSUE TITLE
Agenda is not synced

### ISSUE THREAD

**Issue by sumtopmus** [sumtopmus/sobornyi-bot#54]
The published agenda is not synced after adding new events.

**Comment by sumtopmus** [comment]
Missing access to the channel's `chat_data` from the private user-to-bot chat:

```
2024-09-30 07:00:02,524 - handlers.error - ERROR - Exception while handling the update None:
Traceback (most recent call last):
  File "/envs/sobornyi-bot/lib/python3.12/site-packages/telegram/ext/_jobqueue.py", line 969, in _run
    await self.callback(context)
  File "/projects/sobornyi-bot/src/handlers/calendar/agenda.py", line 45, in publish_agenda
    await cross_post(message, context)
  File "/projects/sobornyi-bot/src/handlers/channel.py", line 54, in cross_post
    context.chat_data["cross-posts"][message.id] = copy.message_id
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```
